name: Build and Push Rasa Docker Image

# Chạy khi có push lên main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout mã nguồn
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. (Tùy chọn) Thiết lập QEMU để hỗ trợ multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Thiết lập Docker Buildx (BuildKit)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build và push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rasa:1.0
